In [1]:
# Import the numpy library
import numpy as np

In [2]:
# Create the "grades" array 
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [3]:
# Use numpy functions to calculate the mean, median, and standard deviation of the grades.

# mean
grade_mean = np.mean(grades)

# median
grade_median = np.median(grades)

#standard deviation
grade_std = np.std(grades)

print(f"Mean: {grade_mean}\nMedian: {grade_median}\nStandard Deviation: {grade_std}")

Mean: 87.5
Median: 88.5
Standard Deviation: 6.591661399070799


In [4]:
# Use numpy function to find the maximum and minimum of the grades.

# maximum
grade_max = np.max(grades)

# minimum
grade_min = np.min(grades)

print(f"Maximum Grade: {grade_max}\nMinimum Grade: {grade_min}")

Maximum Grade: 98
Minimum Grade: 75


In [5]:
# Use numpy function to sort the grades in ascending order.
grade_sort = np.sort(grades)
grade_sort

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [6]:
# Use numpy function to find the index of the highest grade in the array.
max_index = np.argmax(grades)
max_index

7

In [7]:
# Use numpy function to count the number of students who scored above 90.
grade_count = np.count_nonzero(grades > 90)
print(f"The number of students that scored above 90 are: {grade_count}")

The number of students that scored above 90 are: 3


In [8]:
# Use numpy function to calculate the percentage of students who scored above 90.
len_scores = len(grades)

student_perct = int(grade_count/len_scores * 100)

print(f"The percentage of students that scored above 90 are: {student_perct}%")

The percentage of students that scored above 90 are: 30%


In [9]:
# Use numpy function to calculate the percentage of students who scored below 75.
student_75_score = np.count_nonzero(grades < 75)

student_75_percent = int(student_75_score/len_scores * 100)

print(f"The percentage of students that scored below 75 is: {student_75_percent}%")

The percentage of students that scored below 75 is: 0%


In [10]:
# Use numpy function to extract all the grades above 90 and put them in a new array called "high_performers"
high_performers = grades[grades > 90]
high_performers

array([92, 95, 98])

In [11]:
# Create a new array called "passing_grades" that contains all the grades above 75.
passing_grades = grades[grades > 75]
passing_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])